// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8yowgKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxJDCgxBZGRDaGFyYWN0ZXISFi5wcm90b2J1Zi5DaGFyYWN0",
            "ZXJNc2caGS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARI3CgZHZXRNYXAS",
            "FS5wcm90b2J1Zi5OdWxsUmVxdWVzdBoWLnByb3RvYnVmLk1lc3NhZ2VPZk1h",
            "cBIsCgRNb3ZlEhEucHJvdG9idWYuTW92ZU1zZxoRLnByb3RvYnVmLk1vdmVS",
            "ZXMSMgoHUmVjb3ZlchIULnByb3RvYnVmLlJlY292ZXJNc2caES5wcm90b2J1",
            "Zi5Cb29sUmVzEi0KB1Byb2R1Y2USDy5wcm90b2J1Zi5JRE1zZxoRLnByb3Rv",
            "YnVmLkJvb2xSZXMSNAoHUmVidWlsZBIWLnByb3RvYnVmLkNvbnN0cnVjdE1z",
            "ZxoRLnByb3RvYnVmLkJvb2xSZXMSNgoJQ29uc3RydWN0EhYucHJvdG9idWYu",
            "Q29uc3RydWN0TXNnGhEucHJvdG9idWYuQm9vbFJlcxI+Cg1Db25zdHJ1Y3RU",
            "cmFwEhoucHJvdG9idWYuQ29uc3RydWN0VHJhcE1zZxoRLnByb3RvYnVmLkJv",
            "b2xSZXMSLgoFRXF1aXASEi5wcm90b2J1Zi5FcXVpcE1zZxoRLnByb3RvYnVm",
            "LkJvb2xSZXMSMAoGQXR0YWNrEhMucHJvdG9idWYuQXR0YWNrTXNnGhEucHJv",
            "dG9idWYuQm9vbFJlcxIsCgRDYXN0EhEucHJvdG9idWYuQ2FzdE1zZxoRLnBy",
            "b3RvYnVmLkJvb2xSZXMSSAoSQXR0YWNrQ29uc3RydWN0aW9uEh8ucHJvdG9i",
            "dWYuQXR0YWNrQ29uc3RydWN0aW9uTXNnGhEucHJvdG9idWYuQm9vbFJlcxJQ",
            "ChZBdHRhY2tBZGRpdGlvblJlc291cmNlEiMucHJvdG9idWYuQXR0YWNrQWRk",
            "aXRpb25SZXNvdXJjZU1zZxoRLnByb3RvYnVmLkJvb2xSZXMSLAoEU2VuZBIR",
            "LnByb3RvYnVmLlNlbmRNc2caES5wcm90b2J1Zi5Cb29sUmVzEkAKDkNyZWF0",
            "Q2hhcmFjdGVyEhsucHJvdG9idWYuQ3JlYXRDaGFyYWN0ZXJNc2caES5wcm90",
            "b2J1Zi5Cb29sUmVzEk0KEUNyZWF0Q2hhcmFjdGVyUklEEhsucHJvdG9idWYu",
            "Q3JlYXRDaGFyYWN0ZXJNc2caGy5wcm90b2J1Zi5DcmVhdENoYXJhY3RlclJl",
            "cxIyCgxFbmRBbGxBY3Rpb24SDy5wcm90b2J1Zi5JRE1zZxoRLnByb3RvYnVm",
            "LkJvb2xSZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
