// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIcHJvdG9idWYqUAoJR2FtZVN0YXRlEhMK",
            "D05VTExfR0FNRV9TVEFURRAAEg4KCkdBTUVfU1RBUlQQARIQCgxHQU1FX1JV",
            "Tk5JTkcQAhIMCghHQU1FX0VORBADKpUBCglQbGFjZVR5cGUSEwoPTlVMTF9Q",
            "TEFDRV9UWVBFEAASCAoESE9NRRABEgkKBVNQQUNFEAISCwoHQkFSUklFUhAD",
            "EggKBEJVU0gQBBIUChBFQ09OT01ZX1JFU09VUkNFEAUSFQoRQURESVRJT05f",
            "UkVTT1VSQ0UQBhIQCgxDT05TVFJVQ1RJT04QBxIICgRUUkFQEAgqOAoJU2hh",
            "cGVUeXBlEhMKD05VTExfU0hBUEVfVFlQRRAAEgoKBkNJUkNMRRABEgoKBlNR",
            "VUFSRRACKjsKClBsYXllclR5cGUSFAoQTlVMTF9QTEFZRVJfVFlQRRAAEg0K",
            "CUNIQVJBQ1RFUhABEggKBFRFQU0QAirPAQoNQ2hhcmFjdGVyVHlwZRIXChNO",
            "VUxMX0NIQVJBQ1RFUl9UWVBFEAASDAoIVGFuZ1NlbmcQARINCglTdW5XdWtv",
            "bmcQAhIMCghaaHVCYWppZRADEg0KCVNoYVd1amluZxAEEg0KCUJhaUxvbmdt",
            "YRAFEgoKBk1vbmtpZBAGEgsKB0ppdUxpbmcQBxINCglIb25nSGFpZXIQCBIN",
            "CglOaXVNb3dhbmcQCRILCgdUaWVTaGFuEAoSDgoKWmhpWmh1amluZxALEggK",
            "BFBhd24QDCrxAQoOQ2hhcmFjdGVyU3RhdGUSGAoUTlVMTF9DSEFSQUNURVJf",
            "U1RBVEUQABIICgRJRExFEAESDgoKSEFSVkVTVElORxACEg0KCUFUVEFDS0lO",
            "RxADEhEKDVNLSUxMX0NBU1RJTkcQBBIQCgxDT05TVFJVQ1RJTkcQBRIKCgZN",
            "T1ZJTkcQBhIJCgVCTElORBAHEhAKDEtOT0NLRURfQkFDSxAIEgsKB1NUVU5O",
            "RUQQCRINCglJTlZJU0lCTEUQChILCgdIRUFMSU5HEAsSCwoHQkVSU0VSSxAM",
            "EgoKBkJVUk5FRBANEgwKCERFQ0VBU0VEEA4qmgEKEUNoYXJhY3RlckJ1ZmZU",
            "eXBlEhwKGE5VTExfQ0hBUkFDVEVSX0JVRkZfVFlQRRAAEhAKDEFUVEFDS19C",
            "VUZGMRABEhAKDEFUVEFDS19CVUZGMhACEhAKDEFUVEFDS19CVUZGMxADEhAK",
            "DERFRkVOU0VfQlVGRhAEEg4KClNQRUVEX0JVRkYQBRIPCgtWSVNJT05fQlVG",
            "RhAGKooBChNFY29ub215UmVzb3VyY2VUeXBlEh4KGk5VTExfRUNPTk9NWV9S",
            "RVNPVVJDRV9UWVBFEAASGgoWU01BTExfRUNPTk9NWV9SRVNPVVJDRRABEhsK",
            "F01FRElVTV9FQ09OT01ZX1JFU09VUkNFEAISGgoWTEFSR0VfRUNPTk9NWV9S",
            "RVNPVVJDRRADKrYBChRBZGRpdGlvblJlc291cmNlVHlwZRIfChtOVUxMX0FE",
            "RElUSU9OX1JFU09VUkNFX1RZUEUQABIOCgpMSUZFX1BPT0wxEAESDgoKTElG",
            "RV9QT09MMhACEg4KCkxJRkVfUE9PTDMQAxIOCgpDUkFaWV9NQU4xEAQSDgoK",
            "Q1JBWllfTUFOMhAFEg4KCkNSQVpZX01BTjMQBhIOCgpRVUlDS19TVEVQEAcS",
            "DQoJV0lERV9WSUVXEAgqbAoURWNvbm9teVJlc291cmNlU3RhdGUSHwobTlVM",
            "TF9FQ09OT01ZX1JFU09VUkNFX1NUU1RFEAASDwoLSEFSVkVTVEFCTEUQARIT",
            "Cg9CRUlOR19IQVJWRVNURUQQAhINCglIQVJWRVNURUQQAyplChVBZGRpdGlv",
            "blJlc291cmNlU3RhdGUSIAocTlVMTF9BRERJVElPTl9SRVNPVVJDRV9TVEFU",
            "RRAAEgwKCEJFQVRBQkxFEAESEAoMQkVJTkdfQkVBVEVOEAISCgoGQkVBVEVO",
            "EAMqgQIKDUVxdWlwbWVudFR5cGUSFwoTTlVMTF9FUVVJUE1FTlRfVFlQRRAA",
            "EhcKE1NNQUxMX0hFQUxUSF9QT1RJT04QARIYChRNRURJVU1fSEVBTFRIX1BP",
            "VElPThACEhcKE0xBUkdFX0hFQUxUSF9QT1RJT04QAxIQCgxTTUFMTF9TSElF",
            "TEQQBBIRCg1NRURJVU1fU0hJRUxEEAUSEAoMTEFSR0VfU0hJRUxEEAYSDgoK",
            "U1BFRURCT09UUxAHEhcKE1BVUklGSUNBVElPTl9QT1RJT04QCBIXChNJTlZJ",
            "U0lCSUxJVFlfUE9USU9OEAkSEgoOQkVSU0VSS19QT1RJT04QCipSChBDb25z",
            "dHJ1Y3Rpb25UeXBlEhoKFk5VTExfQ09OU1RSVUNUSU9OX1RZUEUQABIMCghC",
            "QVJSQUNLUxABEgoKBlNQUklORxACEggKBEZBUk0QAyoyCghUcmFwVHlwZRIS",
            "Cg5OVUxMX1RSQVBfVFlQRRAAEggKBEhPTEUQARIICgRDQUdFEAIqNAoITmV3",
            "c1R5cGUSEgoOTlVMTF9ORVdTX1RZUEUQABIICgRURVhUEAESCgoGQklOQVJZ",
            "EAIqQgoKUGxheWVyVGVhbRINCglOVUxMX1RFQU0QABISCg5CVURESElTVFNf",
            "VEVBTRABEhEKDU1PTlNURVJTX1RFQU0QAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.GameState), typeof(global::Protobuf.PlaceType), typeof(global::Protobuf.ShapeType), typeof(global::Protobuf.PlayerType), typeof(global::Protobuf.CharacterType), typeof(global::Protobuf.CharacterState), typeof(global::Protobuf.CharacterBuffType), typeof(global::Protobuf.EconomyResourceType), typeof(global::Protobuf.AdditionResourceType), typeof(global::Protobuf.EconomyResourceState), typeof(global::Protobuf.AdditionResourceState), typeof(global::Protobuf.EquipmentType), typeof(global::Protobuf.ConstructionType), typeof(global::Protobuf.TrapType), typeof(global::Protobuf.NewsType), typeof(global::Protobuf.PlayerTeam), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GameState {
    [pbr::OriginalName("NULL_GAME_STATE")] NullGameState = 0,
    [pbr::OriginalName("GAME_START")] GameStart = 1,
    [pbr::OriginalName("GAME_RUNNING")] GameRunning = 2,
    [pbr::OriginalName("GAME_END")] GameEnd = 3,
  }

  public enum PlaceType {
    [pbr::OriginalName("NULL_PLACE_TYPE")] NullPlaceType = 0,
    /// <summary>
    /// 出生点（地图左下与右上）
    /// </summary>
    [pbr::OriginalName("HOME")] Home = 1,
    /// <summary>
    /// 空地
    /// </summary>
    [pbr::OriginalName("SPACE")] Space = 2,
    /// <summary>
    /// 障碍
    /// </summary>
    [pbr::OriginalName("BARRIER")] Barrier = 3,
    /// <summary>
    /// 草丛
    /// </summary>
    [pbr::OriginalName("BUSH")] Bush = 4,
    /// <summary>
    /// 经济资源
    /// </summary>
    [pbr::OriginalName("ECONOMY_RESOURCE")] EconomyResource = 5,
    /// <summary>
    /// 加成资源
    /// </summary>
    [pbr::OriginalName("ADDITION_RESOURCE")] AdditionResource = 6,
    /// <summary>
    /// 建筑
    /// </summary>
    [pbr::OriginalName("CONSTRUCTION")] Construction = 7,
    /// <summary>
    /// 陷阱
    /// </summary>
    [pbr::OriginalName("TRAP")] Trap = 8,
  }

  public enum ShapeType {
    [pbr::OriginalName("NULL_SHAPE_TYPE")] NullShapeType = 0,
    [pbr::OriginalName("CIRCLE")] Circle = 1,
    [pbr::OriginalName("SQUARE")] Square = 2,
  }

  public enum PlayerType {
    [pbr::OriginalName("NULL_PLAYER_TYPE")] NullPlayerType = 0,
    [pbr::OriginalName("CHARACTER")] Character = 1,
    [pbr::OriginalName("TEAM")] Team = 2,
  }

  public enum CharacterType {
    [pbr::OriginalName("NULL_CHARACTER_TYPE")] NullCharacterType = 0,
    /// <summary>
    /// 取经团队阵营角色
    /// </summary>
    [pbr::OriginalName("TangSeng")] TangSeng = 1,
    [pbr::OriginalName("SunWukong")] SunWukong = 2,
    [pbr::OriginalName("ZhuBajie")] ZhuBajie = 3,
    [pbr::OriginalName("ShaWujing")] ShaWujing = 4,
    [pbr::OriginalName("BaiLongma")] BaiLongma = 5,
    [pbr::OriginalName("Monkid")] Monkid = 6,
    /// <summary>
    /// 妖怪团队阵营角色
    /// </summary>
    [pbr::OriginalName("JiuLing")] JiuLing = 7,
    [pbr::OriginalName("HongHaier")] HongHaier = 8,
    [pbr::OriginalName("NiuMowang")] NiuMowang = 9,
    [pbr::OriginalName("TieShan")] TieShan = 10,
    [pbr::OriginalName("ZhiZhujing")] ZhiZhujing = 11,
    [pbr::OriginalName("Pawn")] Pawn = 12,
  }

  public enum CharacterState {
    [pbr::OriginalName("NULL_CHARACTER_STATE")] NullCharacterState = 0,
    [pbr::OriginalName("IDLE")] Idle = 1,
    [pbr::OriginalName("HARVESTING")] Harvesting = 2,
    [pbr::OriginalName("ATTACKING")] Attacking = 3,
    [pbr::OriginalName("SKILL_CASTING")] SkillCasting = 4,
    [pbr::OriginalName("CONSTRUCTING")] Constructing = 5,
    [pbr::OriginalName("MOVING")] Moving = 6,
    [pbr::OriginalName("BLIND")] Blind = 7,
    [pbr::OriginalName("KNOCKED_BACK")] KnockedBack = 8,
    [pbr::OriginalName("STUNNED")] Stunned = 9,
    [pbr::OriginalName("INVISIBLE")] Invisible = 10,
    [pbr::OriginalName("HEALING")] Healing = 11,
    [pbr::OriginalName("BERSERK")] Berserk = 12,
    [pbr::OriginalName("BURNED")] Burned = 13,
    /// <summary>
    /// HARM_CUT = 14;
    /// </summary>
    [pbr::OriginalName("DECEASED")] Deceased = 14,
  }

  public enum CharacterBuffType {
    [pbr::OriginalName("NULL_CHARACTER_BUFF_TYPE")] NullCharacterBuffType = 0,
    [pbr::OriginalName("ATTACK_BUFF1")] AttackBuff1 = 1,
    [pbr::OriginalName("ATTACK_BUFF2")] AttackBuff2 = 2,
    [pbr::OriginalName("ATTACK_BUFF3")] AttackBuff3 = 3,
    [pbr::OriginalName("DEFENSE_BUFF")] DefenseBuff = 4,
    [pbr::OriginalName("SPEED_BUFF")] SpeedBuff = 5,
    [pbr::OriginalName("VISION_BUFF")] VisionBuff = 6,
  }

  public enum EconomyResourceType {
    [pbr::OriginalName("NULL_ECONOMY_RESOURCE_TYPE")] NullEconomyResourceType = 0,
    [pbr::OriginalName("SMALL_ECONOMY_RESOURCE")] SmallEconomyResource = 1,
    [pbr::OriginalName("MEDIUM_ECONOMY_RESOURCE")] MediumEconomyResource = 2,
    [pbr::OriginalName("LARGE_ECONOMY_RESOURCE")] LargeEconomyResource = 3,
  }

  public enum AdditionResourceType {
    [pbr::OriginalName("NULL_ADDITION_RESOURCE_TYPE")] NullAdditionResourceType = 0,
    [pbr::OriginalName("LIFE_POOL1")] LifePool1 = 1,
    [pbr::OriginalName("LIFE_POOL2")] LifePool2 = 2,
    [pbr::OriginalName("LIFE_POOL3")] LifePool3 = 3,
    [pbr::OriginalName("CRAZY_MAN1")] CrazyMan1 = 4,
    [pbr::OriginalName("CRAZY_MAN2")] CrazyMan2 = 5,
    [pbr::OriginalName("CRAZY_MAN3")] CrazyMan3 = 6,
    [pbr::OriginalName("QUICK_STEP")] QuickStep = 7,
    [pbr::OriginalName("WIDE_VIEW")] WideView = 8,
  }

  public enum EconomyResourceState {
    [pbr::OriginalName("NULL_ECONOMY_RESOURCE_STSTE")] NullEconomyResourceStste = 0,
    [pbr::OriginalName("HARVESTABLE")] Harvestable = 1,
    [pbr::OriginalName("BEING_HARVESTED")] BeingHarvested = 2,
    [pbr::OriginalName("HARVESTED")] Harvested = 3,
  }

  public enum AdditionResourceState {
    [pbr::OriginalName("NULL_ADDITION_RESOURCE_STATE")] NullAdditionResourceState = 0,
    [pbr::OriginalName("BEATABLE")] Beatable = 1,
    [pbr::OriginalName("BEING_BEATEN")] BeingBeaten = 2,
    [pbr::OriginalName("BEATEN")] Beaten = 3,
  }

  public enum EquipmentType {
    [pbr::OriginalName("NULL_EQUIPMENT_TYPE")] NullEquipmentType = 0,
    [pbr::OriginalName("SMALL_HEALTH_POTION")] SmallHealthPotion = 1,
    [pbr::OriginalName("MEDIUM_HEALTH_POTION")] MediumHealthPotion = 2,
    [pbr::OriginalName("LARGE_HEALTH_POTION")] LargeHealthPotion = 3,
    [pbr::OriginalName("SMALL_SHIELD")] SmallShield = 4,
    [pbr::OriginalName("MEDIUM_SHIELD")] MediumShield = 5,
    [pbr::OriginalName("LARGE_SHIELD")] LargeShield = 6,
    [pbr::OriginalName("SPEEDBOOTS")] Speedboots = 7,
    [pbr::OriginalName("PURIFICATION_POTION")] PurificationPotion = 8,
    [pbr::OriginalName("INVISIBILITY_POTION")] InvisibilityPotion = 9,
    [pbr::OriginalName("BERSERK_POTION")] BerserkPotion = 10,
  }

  public enum ConstructionType {
    [pbr::OriginalName("NULL_CONSTRUCTION_TYPE")] NullConstructionType = 0,
    [pbr::OriginalName("BARRACKS")] Barracks = 1,
    [pbr::OriginalName("SPRING")] Spring = 2,
    [pbr::OriginalName("FARM")] Farm = 3,
  }

  public enum TrapType {
    [pbr::OriginalName("NULL_TRAP_TYPE")] NullTrapType = 0,
    /// <summary>
    /// 坑洞陷阱
    /// </summary>
    [pbr::OriginalName("HOLE")] Hole = 1,
    /// <summary>
    /// 牢笼陷阱
    /// </summary>
    [pbr::OriginalName("CAGE")] Cage = 2,
  }

  public enum NewsType {
    [pbr::OriginalName("NULL_NEWS_TYPE")] NullNewsType = 0,
    [pbr::OriginalName("TEXT")] Text = 1,
    [pbr::OriginalName("BINARY")] Binary = 2,
  }

  public enum PlayerTeam {
    [pbr::OriginalName("NULL_TEAM")] NullTeam = 0,
    [pbr::OriginalName("BUDDHISTS_TEAM")] BuddhistsTeam = 1,
    [pbr::OriginalName("MONSTERS_TEAM")] MonstersTeam = 2,
  }

  #endregion

}

#endregion Designer generated code
