// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf
{

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection
  {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor
    {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection()
    {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIcHJvdG9idWYqUAoJR2FtZVN0YXRlEhMK",
            "D05VTExfR0FNRV9TVEFURRAAEg4KCkdBTUVfU1RBUlQQARIQCgxHQU1FX1JV",
            "Tk5JTkcQAhIMCghHQU1FX0VORBADKpUBCglQbGFjZVR5cGUSEwoPTlVMTF9Q",
            "TEFDRV9UWVBFEAASCAoESE9NRRABEgkKBVNQQUNFEAISCwoHQkFSUklFUhAD",
            "EggKBEJVU0gQBBIUChBFQ09OT01ZX1JFU09VUkNFEAUSFQoRQURESVRJT05f",
            "UkVTT1VSQ0UQBhIQCgxDT05TVFJVQ1RJT04QBxIICgRUUkFQEAgqOAoJU2hh",
            "cGVUeXBlEhMKD05VTExfU0hBUEVfVFlQRRAAEgoKBkNJUkNMRRABEgoKBlNR",
            "VUFSRRACKrACCg1DaGFyYWN0ZXJUeXBlEhcKE05VTExfQ0hBUkFDVEVSX1RZ",
            "UEUQABIUChBDQU1QMV9DSEFSQUNURVIxEAESFAoQQ0FNUDFfQ0hBUkFDVEVS",
            "MhACEhQKEENBTVAxX0NIQVJBQ1RFUjMQAxIUChBDQU1QMV9DSEFSQUNURVI0",
            "EAQSFAoQQ0FNUDFfQ0hBUkFDVEVSNRAFEhQKEENBTVAxX0NIQVJBQ1RFUjYQ",
            "BhIUChBDQU1QMl9DSEFSQUNURVIxEAcSFAoQQ0FNUDJfQ0hBUkFDVEVSMhAI",
            "EhQKEENBTVAyX0NIQVJBQ1RFUjMQCRIUChBDQU1QMl9DSEFSQUNURVI0EAoS",
            "FAoQQ0FNUDJfQ0hBUkFDVEVSNRALEhQKEENBTVAyX0NIQVJBQ1RFUjYQDCrj",
            "AQoOQ2hhcmFjdGVyU3RhdGUSGAoUTlVMTF9DSEFSQUNURVJfU1RBVEUQABII",
            "CgRJRExFEAESDgoKSEFSVkVTVElORxACEg0KCUFUVEFDS0lORxADEhEKDVNL",
            "SUxMX0NBU1RJTkcQBBIQCgxDT05TVFJVQ1RJTkcQBRIKCgZNT1ZJTkcQBhIJ",
            "CgVCTElORBAHEhAKDEtOT0NLRURfQkFDSxAIEgsKB1NUVU5ORUQQCRINCglJ",
            "TlZJU0lCTEUQChILCgdIRUFMSU5HEAsSCwoHQkVSU0VSSxAMEgoKBkJVUk5F",
            "RBANKooBChNFY29ub215UmVzb3VyY2VUeXBlEh4KGk5VTExfRUNPTk9NWV9S",
            "RVNPVVJDRV9UWVBFEAASGgoWU01BTExfRUNPTk9NWV9SRVNPVVJDRRABEhsK",
            "F01FRElVTV9FQ09OT01ZX1JFU09VUkNFEAISGgoWTEFSR0VfRUNPTk9NWV9S",
            "RVNPVVJDRRADKp0CChRBZGRpdGlvblJlc291cmNlVHlwZRIfChtOVUxMX0FE",
            "RElUSU9OX1JFU09VUkNFX1RZUEUQABIcChhTTUFMTF9BRERJVElPTl9SRVNP",
            "VVJDRTEQARIdChlNRURJVU1fQURESVRJT05fUkVTT1VSQ0UxEAISHAoYTEFS",
            "R0VfQURESVRJT05fUkVTT1VSQ0UxEAMSHAoYU01BTExfQURESVRJT05fUkVT",
            "T1VSQ0UyEAQSHQoZTUVESVVNX0FERElUSU9OX1JFU09VUkNFMhAFEhwKGExB",
            "UkdFX0FERElUSU9OX1JFU09VUkNFMhAGEhYKEkFERElUSU9OX1JFU09VUkNF",
            "MxAHEhYKEkFERElUSU9OX1JFU09VUkNFNBAIKmwKFEVjb25vbXlSZXNvdXJj",
            "ZVN0YXRlEh8KG05VTExfRUNPTk9NWV9SRVNPVVJDRV9TVFNURRAAEg8KC0hB",
            "UlZFU1RBQkxFEAESEwoPQkVJTkdfSEFSVkVTVEVEEAISDQoJSEFSVkVTVEVE",
            "EAMqZQoVQWRkaXRpb25SZXNvdXJjZVN0YXRlEiAKHE5VTExfQURESVRJT05f",
            "UkVTT1VSQ0VfU1RBVEUQABIMCghCRUFUQUJMRRABEhAKDEJFSU5HX0JFQVRF",
            "ThACEgoKBkJFQVRFThADKoECCg1FcXVpcG1lbnRUeXBlEhcKE05VTExfRVFV",
            "SVBNRU5UX1RZUEUQABIXChNTTUFMTF9IRUFMVEhfUE9USU9OEAESGAoUTUVE",
            "SVVNX0hFQUxUSF9QT1RJT04QAhIXChNMQVJHRV9IRUFMVEhfUE9USU9OEAMS",
            "EAoMU01BTExfU0hJRUxEEAQSEQoNTUVESVVNX1NISUVMRBAFEhAKDExBUkdF",
            "X1NISUVMRBAGEg4KClNQRUVEQk9PVFMQBxIXChNQVVJJRklDQVRJT05fUE9U",
            "SU9OEAgSFwoTSU5WSVNJQklMSVRZX1BPVElPThAJEhIKDkJFUlNFUktfUE9U",
            "SU9OEAoqUgoQQ29uc3RydWN0aW9uVHlwZRIaChZOVUxMX0NPTlNUUlVDVElP",
            "Tl9UWVBFEAASDAoIQkFSUkFDS1MQARIKCgZTUFJJTkcQAhIICgRGQVJNEAMq",
            "MgoIVHJhcFR5cGUSEgoOTlVMTF9UUkFQX1RZUEUQABIICgRIT0xFEAESCAoE",
            "Q0FHRRACKjQKCE5ld3NUeXBlEhIKDk5VTExfTkVXU19UWVBFEAASCAoEVEVY",
            "VBABEgoKBkJJTkFSWRACKkIKClBsYXllclRlYW0SDQoJTlVMTF9URUFNEAAS",
            "EgoOQlVEREhJU1RTX1RFQU0QARIRCg1NT05TVEVSU19URUFNEAJiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] { typeof(global::Protobuf.GameState), typeof(global::Protobuf.PlaceType), typeof(global::Protobuf.ShapeType), typeof(global::Protobuf.CharacterType), typeof(global::Protobuf.CharacterState), typeof(global::Protobuf.EconomyResourceType), typeof(global::Protobuf.AdditionResourceType), typeof(global::Protobuf.EconomyResourceState), typeof(global::Protobuf.AdditionResourceState), typeof(global::Protobuf.EquipmentType), typeof(global::Protobuf.ConstructionType), typeof(global::Protobuf.TrapType), typeof(global::Protobuf.NewsType), typeof(global::Protobuf.PlayerTeam), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GameState
  {
    [pbr::OriginalName("NULL_GAME_STATE")] NullGameState = 0,
    [pbr::OriginalName("GAME_START")] GameStart = 1,
    [pbr::OriginalName("GAME_RUNNING")] GameRunning = 2,
    [pbr::OriginalName("GAME_END")] GameEnd = 3,
  }

  public enum PlaceType
  {
    [pbr::OriginalName("NULL_PLACE_TYPE")] NullPlaceType = 0,
    /// <summary>
    /// 出生点（地图左下与右上）
    /// </summary>
    [pbr::OriginalName("HOME")] Home = 1,
    /// <summary>
    /// 空地
    /// </summary>
    [pbr::OriginalName("SPACE")] Space = 2,
    /// <summary>
    /// 障碍
    /// </summary>
    [pbr::OriginalName("BARRIER")] Barrier = 3,
    /// <summary>
    /// 草丛
    /// </summary>
    [pbr::OriginalName("BUSH")] Bush = 4,
    /// <summary>
    /// 经济资源
    /// </summary>
    [pbr::OriginalName("ECONOMY_RESOURCE")] EconomyResource = 5,
    /// <summary>
    /// 加成资源
    /// </summary>
    [pbr::OriginalName("ADDITION_RESOURCE")] AdditionResource = 6,
    /// <summary>
    /// 建筑
    /// </summary>
    [pbr::OriginalName("CONSTRUCTION")] Construction = 7,
    /// <summary>
    /// 陷阱
    /// </summary>
    [pbr::OriginalName("TRAP")] Trap = 8,
  }

  public enum ShapeType
  {
    [pbr::OriginalName("NULL_SHAPE_TYPE")] NullShapeType = 0,
    [pbr::OriginalName("CIRCLE")] Circle = 1,
    [pbr::OriginalName("SQUARE")] Square = 2,
  }

  public enum CharacterType
  {
    [pbr::OriginalName("NULL_CHARACTER_TYPE")] NullCharacterType = 0,
    /// <summary>
    /// 取经团队阵营角色
    /// </summary>
    [pbr::OriginalName("CAMP1_CHARACTER1")] Camp1Character1 = 1,
    [pbr::OriginalName("CAMP1_CHARACTER2")] Camp1Character2 = 2,
    [pbr::OriginalName("CAMP1_CHARACTER3")] Camp1Character3 = 3,
    [pbr::OriginalName("CAMP1_CHARACTER4")] Camp1Character4 = 4,
    [pbr::OriginalName("CAMP1_CHARACTER5")] Camp1Character5 = 5,
    [pbr::OriginalName("CAMP1_CHARACTER6")] Camp1Character6 = 6,
    /// <summary>
    /// 妖怪团队阵营角色
    /// </summary>
    [pbr::OriginalName("CAMP2_CHARACTER1")] Camp2Character1 = 7,
    [pbr::OriginalName("CAMP2_CHARACTER2")] Camp2Character2 = 8,
    [pbr::OriginalName("CAMP2_CHARACTER3")] Camp2Character3 = 9,
    [pbr::OriginalName("CAMP2_CHARACTER4")] Camp2Character4 = 10,
    [pbr::OriginalName("CAMP2_CHARACTER5")] Camp2Character5 = 11,
    [pbr::OriginalName("CAMP2_CHARACTER6")] Camp2Character6 = 12,
  }

  public enum CharacterState
  {
    [pbr::OriginalName("NULL_CHARACTER_STATE")] NullCharacterState = 0,
    /// <summary>
    /// 主动状态
    /// </summary>
    [pbr::OriginalName("IDLE")] Idle = 1,
    [pbr::OriginalName("HARVESTING")] Harvesting = 2,
    [pbr::OriginalName("ATTACKING")] Attacking = 3,
    [pbr::OriginalName("SKILL_CASTING")] SkillCasting = 4,
    [pbr::OriginalName("CONSTRUCTING")] Constructing = 5,
    [pbr::OriginalName("MOVING")] Moving = 6,
    /// <summary>
    /// 被动状态
    /// </summary>
    [pbr::OriginalName("BLIND")] Blind = 7,
    [pbr::OriginalName("KNOCKED_BACK")] KnockedBack = 8,
    [pbr::OriginalName("STUNNED")] Stunned = 9,
    [pbr::OriginalName("INVISIBLE")] Invisible = 10,
    [pbr::OriginalName("HEALING")] Healing = 11,
    [pbr::OriginalName("BERSERK")] Berserk = 12,
    [pbr::OriginalName("BURNED")] Burned = 13,
    [pbr::OriginalName("BURNED")] Deceased = 14,

  }

  public enum EconomyResourceType
  {
    [pbr::OriginalName("NULL_ECONOMY_RESOURCE_TYPE")] NullEconomyResourceType = 0,
    [pbr::OriginalName("SMALL_ECONOMY_RESOURCE")] SmallEconomyResource = 1,
    [pbr::OriginalName("MEDIUM_ECONOMY_RESOURCE")] MediumEconomyResource = 2,
    [pbr::OriginalName("LARGE_ECONOMY_RESOURCE")] LargeEconomyResource = 3,
  }

  public enum AdditionResourceType
  {
    [pbr::OriginalName("NULL_ADDITION_RESOURCE_TYPE")] NULL = 0,
    [pbr::OriginalName("LIFE_POOL1")] LIFE_POOL1 = 1,
    [pbr::OriginalName("LIFE_POOL2")] LIFE_POOL2 = 2,
    [pbr::OriginalName("LIFE_POOL3")] LIFE_POOL3 = 3,
    [pbr::OriginalName("CRAZY_MAN1")] CRAZY_MAN1 = 4,
    [pbr::OriginalName("CRAZY_MAN2")] CRAZY_MAN2 = 5,
    [pbr::OriginalName("CRAZY_MAN3")] CRAZY_MAN3 = 6,
    [pbr::OriginalName("QUICK_STEP")] QUICK_STEP = 7,
    [pbr::OriginalName("WIDE_VIEW")] WIDE_VIEW = 8,
  }

  public enum EconomyResourceState
  {
    [pbr::OriginalName("NULL_ECONOMY_RESOURCE_STSTE")] NullEconomyResourceStste = 0,
    [pbr::OriginalName("HARVESTABLE")] Harvestable = 1,
    [pbr::OriginalName("BEING_HARVESTED")] BeingHarvested = 2,
    [pbr::OriginalName("HARVESTED")] Harvested = 3,
  }

  public enum AdditionResourceState
  {
    [pbr::OriginalName("NULL_ADDITION_RESOURCE_STATE")] NullAdditionResourceState = 0,
    [pbr::OriginalName("BEATABLE")] Beatable = 1,
    [pbr::OriginalName("BEING_BEATEN")] BeingBeaten = 2,
    [pbr::OriginalName("BEATEN")] Beaten = 3,
  }

  public enum EquipmentType
  {
    [pbr::OriginalName("NULL_EQUIPMENT_TYPE")] NullEquipmentType = 0,
    [pbr::OriginalName("SMALL_HEALTH_POTION")] SmallHealthPotion = 1,
    [pbr::OriginalName("MEDIUM_HEALTH_POTION")] MediumHealthPotion = 2,
    [pbr::OriginalName("LARGE_HEALTH_POTION")] LargeHealthPotion = 3,
    [pbr::OriginalName("SMALL_SHIELD")] SmallShield = 4,
    [pbr::OriginalName("MEDIUM_SHIELD")] MediumShield = 5,
    [pbr::OriginalName("LARGE_SHIELD")] LargeShield = 6,
    [pbr::OriginalName("SPEEDBOOTS")] Speedboots = 7,
    [pbr::OriginalName("PURIFICATION_POTION")] PurificationPotion = 8,
    [pbr::OriginalName("INVISIBILITY_POTION")] InvisibilityPotion = 9,
    [pbr::OriginalName("BERSERK_POTION")] BerserkPotion = 10,
  }

  public enum ConstructionType
  {
    [pbr::OriginalName("NULL_CONSTRUCTION_TYPE")] NullConstructionType = 0,
    [pbr::OriginalName("BARRACKS")] Barracks = 1,
    [pbr::OriginalName("SPRING")] Spring = 2,
    [pbr::OriginalName("FARM")] Farm = 3,
  }

  public enum TrapType
  {
    [pbr::OriginalName("NULL_TRAP_TYPE")] NullTrapType = 0,
    /// <summary>
    /// 坑洞陷阱
    /// </summary>
    [pbr::OriginalName("HOLE")] Hole = 1,
    /// <summary>
    /// 牢笼陷阱
    /// </summary>
    [pbr::OriginalName("CAGE")] Cage = 2,
  }

  public enum NewsType
  {
    [pbr::OriginalName("NULL_NEWS_TYPE")] NullNewsType = 0,
    [pbr::OriginalName("TEXT")] Text = 1,
    [pbr::OriginalName("BINARY")] Binary = 2,
  }

  public enum PlayerTeam
  {
    [pbr::OriginalName("NULL_TEAM")] NullTeam = 0,
    [pbr::OriginalName("BUDDHISTS_TEAM")] BuddhistsTeam = 1,
    [pbr::OriginalName("MONSTERS_TEAM")] MonstersTeam = 2,
  }

  #endregion

}

#endregion Designer generated code
