// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8yxwYKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxJDCgxBZGRDaGFyYWN0ZXISFi5wcm90b2J1Zi5DaGFyYWN0",
            "ZXJNc2caGS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARI3CgZHZXRNYXAS",
            "FS5wcm90b2J1Zi5OdWxsUmVxdWVzdBoWLnByb3RvYnVmLk1lc3NhZ2VPZk1h",
            "cBIsCgRNb3ZlEhEucHJvdG9idWYuTW92ZU1zZxoRLnByb3RvYnVmLk1vdmVS",
            "ZXMSMgoHUmVjb3ZlchIULnByb3RvYnVmLlJlY292ZXJNc2caES5wcm90b2J1",
            "Zi5Cb29sUmVzEi0KB1Byb2R1Y2USDy5wcm90b2J1Zi5JRE1zZxoRLnByb3Rv",
            "YnVmLkJvb2xSZXMSNAoHUmVidWlsZBIWLnByb3RvYnVmLkNvbnN0cnVjdE1z",
            "ZxoRLnByb3RvYnVmLkJvb2xSZXMSNgoJQ29uc3RydWN0EhYucHJvdG9idWYu",
            "Q29uc3RydWN0TXNnGhEucHJvdG9idWYuQm9vbFJlcxIuCgVFcXVpcBISLnBy",
            "b3RvYnVmLkVxdWlwTXNnGhEucHJvdG9idWYuQm9vbFJlcxIwCgZBdHRhY2sS",
            "Ey5wcm90b2J1Zi5BdHRhY2tNc2caES5wcm90b2J1Zi5Cb29sUmVzEiwKBENh",
            "c3QSES5wcm90b2J1Zi5DYXN0TXNnGhEucHJvdG9idWYuQm9vbFJlcxIsCgRT",
            "ZW5kEhEucHJvdG9idWYuU2VuZE1zZxoRLnByb3RvYnVmLkJvb2xSZXMSQAoO",
            "Q3JlYXRDaGFyYWN0ZXISGy5wcm90b2J1Zi5DcmVhdENoYXJhY3Rlck1zZxoR",
            "LnByb3RvYnVmLkJvb2xSZXMSTQoRQ3JlYXRDaGFyYWN0ZXJSSUQSGy5wcm90",
            "b2J1Zi5DcmVhdENoYXJhY3Rlck1zZxobLnByb3RvYnVmLkNyZWF0Q2hhcmFj",
            "dGVyUmVzEjIKDEVuZEFsbEFjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJv",
            "dG9idWYuQm9vbFJlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
