// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MessageType.proto
// Protobuf C++ Version: 5.29.3

#include "MessageType.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {
}  // namespace protobuf
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_MessageType_2eproto[15];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_MessageType_2eproto = nullptr;
const ::uint32_t TableStruct_MessageType_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_MessageType_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021MessageType.proto\022\010protobuf*P\n\tGameSta"
    "te\022\023\n\017NULL_GAME_STATE\020\000\022\016\n\nGAME_START\020\001\022"
    "\020\n\014GAME_RUNNING\020\002\022\014\n\010GAME_END\020\003*\225\001\n\tPlac"
    "eType\022\023\n\017NULL_PLACE_TYPE\020\000\022\010\n\004HOME\020\001\022\t\n\005"
    "SPACE\020\002\022\013\n\007BARRIER\020\003\022\010\n\004BUSH\020\004\022\024\n\020ECONOM"
    "Y_RESOURCE\020\005\022\025\n\021ADDITION_RESOURCE\020\006\022\020\n\014C"
    "ONSTRUCTION\020\007\022\010\n\004TRAP\020\010*8\n\tShapeType\022\023\n\017"
    "NULL_SHAPE_TYPE\020\000\022\n\n\006CIRCLE\020\001\022\n\n\006SQUARE\020"
    "\002*\317\001\n\rCharacterType\022\027\n\023NULL_CHARACTER_TY"
    "PE\020\000\022\014\n\010TangSeng\020\001\022\r\n\tSunWukong\020\002\022\014\n\010Zhu"
    "Bajie\020\003\022\r\n\tShaWujing\020\004\022\r\n\tBaiLongma\020\005\022\n\n"
    "\006Monkid\020\006\022\013\n\007JiuLing\020\007\022\r\n\tHongHaier\020\010\022\r\n"
    "\tNiuMowang\020\t\022\013\n\007TieShan\020\n\022\016\n\nZhiZhujing\020"
    "\013\022\010\n\004Pawn\020\014*\361\001\n\016CharacterState\022\030\n\024NULL_C"
    "HARACTER_STATE\020\000\022\010\n\004IDLE\020\001\022\016\n\nHARVESTING"
    "\020\002\022\r\n\tATTACKING\020\003\022\021\n\rSKILL_CASTING\020\004\022\020\n\014"
    "CONSTRUCTING\020\005\022\n\n\006MOVING\020\006\022\t\n\005BLIND\020\007\022\020\n"
    "\014KNOCKED_BACK\020\010\022\013\n\007STUNNED\020\t\022\r\n\tINVISIBL"
    "E\020\n\022\013\n\007HEALING\020\013\022\013\n\007BERSERK\020\014\022\n\n\006BURNED\020"
    "\r\022\014\n\010DECEASED\020\016*\232\001\n\021CharacterBuffType\022\034\n"
    "\030NULL_CHARACTER_BUFF_TYPE\020\000\022\020\n\014ATTACK_BU"
    "FF1\020\001\022\020\n\014ATTACK_BUFF2\020\002\022\020\n\014ATTACK_BUFF3\020"
    "\003\022\020\n\014DEFENSE_BUFF\020\004\022\016\n\nSPEED_BUFF\020\005\022\017\n\013V"
    "ISION_BUFF\020\006*\212\001\n\023EconomyResourceType\022\036\n\032"
    "NULL_ECONOMY_RESOURCE_TYPE\020\000\022\032\n\026SMALL_EC"
    "ONOMY_RESOURCE\020\001\022\033\n\027MEDIUM_ECONOMY_RESOU"
    "RCE\020\002\022\032\n\026LARGE_ECONOMY_RESOURCE\020\003*\266\001\n\024Ad"
    "ditionResourceType\022\037\n\033NULL_ADDITION_RESO"
    "URCE_TYPE\020\000\022\016\n\nLIFE_POOL1\020\001\022\016\n\nLIFE_POOL"
    "2\020\002\022\016\n\nLIFE_POOL3\020\003\022\016\n\nCRAZY_MAN1\020\004\022\016\n\nC"
    "RAZY_MAN2\020\005\022\016\n\nCRAZY_MAN3\020\006\022\016\n\nQUICK_STE"
    "P\020\007\022\r\n\tWIDE_VIEW\020\010*l\n\024EconomyResourceSta"
    "te\022\037\n\033NULL_ECONOMY_RESOURCE_STSTE\020\000\022\017\n\013H"
    "ARVESTABLE\020\001\022\023\n\017BEING_HARVESTED\020\002\022\r\n\tHAR"
    "VESTED\020\003*e\n\025AdditionResourceState\022 \n\034NUL"
    "L_ADDITION_RESOURCE_STATE\020\000\022\014\n\010BEATABLE\020"
    "\001\022\020\n\014BEING_BEATEN\020\002\022\n\n\006BEATEN\020\003*\201\002\n\rEqui"
    "pmentType\022\027\n\023NULL_EQUIPMENT_TYPE\020\000\022\027\n\023SM"
    "ALL_HEALTH_POTION\020\001\022\030\n\024MEDIUM_HEALTH_POT"
    "ION\020\002\022\027\n\023LARGE_HEALTH_POTION\020\003\022\020\n\014SMALL_"
    "SHIELD\020\004\022\021\n\rMEDIUM_SHIELD\020\005\022\020\n\014LARGE_SHI"
    "ELD\020\006\022\016\n\nSPEEDBOOTS\020\007\022\027\n\023PURIFICATION_PO"
    "TION\020\010\022\027\n\023INVISIBILITY_POTION\020\t\022\022\n\016BERSE"
    "RK_POTION\020\n*R\n\020ConstructionType\022\032\n\026NULL_"
    "CONSTRUCTION_TYPE\020\000\022\014\n\010BARRACKS\020\001\022\n\n\006SPR"
    "ING\020\002\022\010\n\004FARM\020\003*2\n\010TrapType\022\022\n\016NULL_TRAP"
    "_TYPE\020\000\022\010\n\004HOLE\020\001\022\010\n\004CAGE\020\002*4\n\010NewsType\022"
    "\022\n\016NULL_NEWS_TYPE\020\000\022\010\n\004TEXT\020\001\022\n\n\006BINARY\020"
    "\002*B\n\nPlayerTeam\022\r\n\tNULL_TEAM\020\000\022\022\n\016BUDDHI"
    "STS_TEAM\020\001\022\021\n\rMONSTERS_TEAM\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_MessageType_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MessageType_2eproto = {
    false,
    false,
    1997,
    descriptor_table_protodef_MessageType_2eproto,
    "MessageType.proto",
    &descriptor_table_MessageType_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_MessageType_2eproto::offsets,
    file_level_enum_descriptors_MessageType_2eproto,
    file_level_service_descriptors_MessageType_2eproto,
};
namespace protobuf {
const ::google::protobuf::EnumDescriptor* GameState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t GameState_internal_data_[] = {
    262144u, 0u, };
bool GameState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* PlaceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t PlaceType_internal_data_[] = {
    589824u, 0u, };
bool PlaceType_IsValid(int value) {
  return 0 <= value && value <= 8;
}
const ::google::protobuf::EnumDescriptor* ShapeType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t ShapeType_internal_data_[] = {
    196608u, 0u, };
bool ShapeType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* CharacterType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t CharacterType_internal_data_[] = {
    851968u, 0u, };
bool CharacterType_IsValid(int value) {
  return 0 <= value && value <= 12;
}
const ::google::protobuf::EnumDescriptor* CharacterState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t CharacterState_internal_data_[] = {
    983040u, 0u, };
bool CharacterState_IsValid(int value) {
  return 0 <= value && value <= 14;
}
const ::google::protobuf::EnumDescriptor* CharacterBuffType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[5];
}
PROTOBUF_CONSTINIT const uint32_t CharacterBuffType_internal_data_[] = {
    458752u, 0u, };
bool CharacterBuffType_IsValid(int value) {
  return 0 <= value && value <= 6;
}
const ::google::protobuf::EnumDescriptor* EconomyResourceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[6];
}
PROTOBUF_CONSTINIT const uint32_t EconomyResourceType_internal_data_[] = {
    262144u, 0u, };
bool EconomyResourceType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* AdditionResourceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[7];
}
PROTOBUF_CONSTINIT const uint32_t AdditionResourceType_internal_data_[] = {
    589824u, 0u, };
bool AdditionResourceType_IsValid(int value) {
  return 0 <= value && value <= 8;
}
const ::google::protobuf::EnumDescriptor* EconomyResourceState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[8];
}
PROTOBUF_CONSTINIT const uint32_t EconomyResourceState_internal_data_[] = {
    262144u, 0u, };
bool EconomyResourceState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* AdditionResourceState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[9];
}
PROTOBUF_CONSTINIT const uint32_t AdditionResourceState_internal_data_[] = {
    262144u, 0u, };
bool AdditionResourceState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* EquipmentType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[10];
}
PROTOBUF_CONSTINIT const uint32_t EquipmentType_internal_data_[] = {
    720896u, 0u, };
bool EquipmentType_IsValid(int value) {
  return 0 <= value && value <= 10;
}
const ::google::protobuf::EnumDescriptor* ConstructionType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[11];
}
PROTOBUF_CONSTINIT const uint32_t ConstructionType_internal_data_[] = {
    262144u, 0u, };
bool ConstructionType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* TrapType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[12];
}
PROTOBUF_CONSTINIT const uint32_t TrapType_internal_data_[] = {
    196608u, 0u, };
bool TrapType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* NewsType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[13];
}
PROTOBUF_CONSTINIT const uint32_t NewsType_internal_data_[] = {
    196608u, 0u, };
bool NewsType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* PlayerTeam_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[14];
}
PROTOBUF_CONSTINIT const uint32_t PlayerTeam_internal_data_[] = {
    196608u, 0u, };
bool PlayerTeam_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_MessageType_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
