// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MessageType.proto
// Protobuf C++ Version: 5.28.2

#include "MessageType.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf
{
}  // namespace protobuf
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_MessageType_2eproto[14];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_MessageType_2eproto = nullptr;
const ::uint32_t TableStruct_MessageType_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_MessageType_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold
) = {
    "\n\021MessageType.proto\022\010protobuf*P\n\tGameSta"
    "te\022\023\n\017NULL_GAME_STATE\020\000\022\016\n\nGAME_START\020\001\022"
    "\020\n\014GAME_RUNNING\020\002\022\014\n\010GAME_END\020\003*\225\001\n\tPlac"
    "eType\022\023\n\017NULL_PLACE_TYPE\020\000\022\010\n\004HOME\020\001\022\t\n\005"
    "SPACE\020\002\022\013\n\007BARRIER\020\003\022\010\n\004BUSH\020\004\022\024\n\020ECONOM"
    "Y_RESOURCE\020\005\022\025\n\021ADDITION_RESOURCE\020\006\022\020\n\014C"
    "ONSTRUCTION\020\007\022\010\n\004TRAP\020\010*8\n\tShapeType\022\023\n\017"
    "NULL_SHAPE_TYPE\020\000\022\n\n\006CIRCLE\020\001\022\n\n\006SQUARE\020"
    "\002*\260\002\n\rCharacterType\022\027\n\023NULL_CHARACTER_TY"
    "PE\020\000\022\024\n\020CAMP1_CHARACTER1\020\001\022\024\n\020CAMP1_CHAR"
    "ACTER2\020\002\022\024\n\020CAMP1_CHARACTER3\020\003\022\024\n\020CAMP1_"
    "CHARACTER4\020\004\022\024\n\020CAMP1_CHARACTER5\020\005\022\024\n\020CA"
    "MP1_CHARACTER6\020\006\022\024\n\020CAMP2_CHARACTER1\020\007\022\024"
    "\n\020CAMP2_CHARACTER2\020\010\022\024\n\020CAMP2_CHARACTER3"
    "\020\t\022\024\n\020CAMP2_CHARACTER4\020\n\022\024\n\020CAMP2_CHARAC"
    "TER5\020\013\022\024\n\020CAMP2_CHARACTER6\020\014*\343\001\n\016Charact"
    "erState\022\030\n\024NULL_CHARACTER_STATE\020\000\022\010\n\004IDL"
    "E\020\001\022\016\n\nHARVESTING\020\002\022\r\n\tATTACKING\020\003\022\021\n\rSK"
    "ILL_CASTING\020\004\022\020\n\014CONSTRUCTING\020\005\022\n\n\006MOVIN"
    "G\020\006\022\t\n\005BLIND\020\007\022\020\n\014KNOCKED_BACK\020\010\022\013\n\007STUN"
    "NED\020\t\022\r\n\tINVISIBLE\020\n\022\013\n\007HEALING\020\013\022\013\n\007BER"
    "SERK\020\014\022\n\n\006BURNED\020\r*P\n\023EconomyResourceTyp"
    "e\022\036\n\032NULL_ECONOMY_RESOURCE_TYPE\020\000\022\031\n\025ECO"
    "NOMY_RESOURCE_TYPE\020\001*\235\002\n\024AdditionResourc"
    "eType\022\037\n\033NULL_ADDITION_RESOURCE_TYPE\020\000\022\034"
    "\n\030SMALL_ADDITION_RESOURCE1\020\001\022\035\n\031MEDIUM_A"
    "DDITION_RESOURCE1\020\002\022\034\n\030LARGE_ADDITION_RE"
    "SOURCE1\020\003\022\034\n\030SMALL_ADDITION_RESOURCE2\020\004\022"
    "\035\n\031MEDIUM_ADDITION_RESOURCE2\020\005\022\034\n\030LARGE_"
    "ADDITION_RESOURCE2\020\006\022\026\n\022ADDITION_RESOURC"
    "E3\020\007\022\026\n\022ADDITION_RESOURCE4\020\010*l\n\024EconomyR"
    "esourceState\022\037\n\033NULL_ECONOMY_RESOURCE_ST"
    "STE\020\000\022\017\n\013HARVESTABLE\020\001\022\023\n\017BEING_HARVESTE"
    "D\020\002\022\r\n\tHARVESTED\020\003*e\n\025AdditionResourceSt"
    "ate\022 \n\034NULL_ADDITION_RESOURCE_STATE\020\000\022\014\n"
    "\010BEATABLE\020\001\022\020\n\014BEING_BEATEN\020\002\022\n\n\006BEATEN\020"
    "\003*\201\002\n\rEquipmentType\022\027\n\023NULL_EQUIPMENT_TY"
    "PE\020\000\022\027\n\023SMALL_HEALTH_POTION\020\001\022\030\n\024MEDIUM_"
    "HEALTH_POTION\020\002\022\027\n\023LARGE_HEALTH_POTION\020\003"
    "\022\020\n\014SMALL_SHIELD\020\004\022\021\n\rMEDIUM_SHIELD\020\005\022\020\n"
    "\014LARGE_SHIELD\020\006\022\016\n\nSPEEDBOOTS\020\007\022\027\n\023PURIF"
    "ICATION_POTION\020\010\022\027\n\023INVISIBILITY_POTION\020"
    "\t\022\022\n\016BERSERK_POTION\020\n*R\n\020ConstructionTyp"
    "e\022\032\n\026NULL_CONSTRUCTION_TYPE\020\000\022\014\n\010BARRACK"
    "S\020\001\022\n\n\006SPRING\020\002\022\010\n\004FARM\020\003*2\n\010TrapType\022\022\n"
    "\016NULL_TRAP_TYPE\020\000\022\010\n\004HOLE\020\001\022\010\n\004CAGE\020\002*4\n"
    "\010NewsType\022\022\n\016NULL_NEWS_TYPE\020\000\022\010\n\004TEXT\020\001\022"
    "\n\n\006BINARY\020\002*B\n\nPlayerTeam\022\r\n\tNULL_TEAM\020\000"
    "\022\022\n\016BUDDHISTS_TEAM\020\001\022\021\n\rMONSTERS_TEAM\020\002b"
    "\006proto3"};
static ::absl::once_flag descriptor_table_MessageType_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MessageType_2eproto = {
    false,
    false,
    1967,
    descriptor_table_protodef_MessageType_2eproto,
    "MessageType.proto",
    &descriptor_table_MessageType_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_MessageType_2eproto::offsets,
    file_level_enum_descriptors_MessageType_2eproto,
    file_level_service_descriptors_MessageType_2eproto,
};
namespace protobuf
{
    const ::google::protobuf::EnumDescriptor* GameState_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[0];
    }
    PROTOBUF_CONSTINIT const uint32_t GameState_internal_data_[] = {
        262144u,
        0u,
    };
    bool GameState_IsValid(int value)
    {
        return 0 <= value && value <= 3;
    }
    const ::google::protobuf::EnumDescriptor* PlaceType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[1];
    }
    PROTOBUF_CONSTINIT const uint32_t PlaceType_internal_data_[] = {
        589824u,
        0u,
    };
    bool PlaceType_IsValid(int value)
    {
        return 0 <= value && value <= 8;
    }
    const ::google::protobuf::EnumDescriptor* ShapeType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[2];
    }
    PROTOBUF_CONSTINIT const uint32_t ShapeType_internal_data_[] = {
        196608u,
        0u,
    };
    bool ShapeType_IsValid(int value)
    {
        return 0 <= value && value <= 2;
    }
    const ::google::protobuf::EnumDescriptor* CharacterType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[3];
    }
    PROTOBUF_CONSTINIT const uint32_t CharacterType_internal_data_[] = {
        851968u,
        0u,
    };
    bool CharacterType_IsValid(int value)
    {
        return 0 <= value && value <= 12;
    }
    const ::google::protobuf::EnumDescriptor* CharacterState_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[4];
    }
    PROTOBUF_CONSTINIT const uint32_t CharacterState_internal_data_[] = {
        917504u,
        0u,
    };
    bool CharacterState_IsValid(int value)
    {
        return 0 <= value && value <= 13;
    }
    const ::google::protobuf::EnumDescriptor* EconomyResourceType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[5];
    }
    PROTOBUF_CONSTINIT const uint32_t EconomyResourceType_internal_data_[] = {
        131072u,
        0u,
    };
    bool EconomyResourceType_IsValid(int value)
    {
        return 0 <= value && value <= 1;
    }
    const ::google::protobuf::EnumDescriptor* AdditionResourceType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[6];
    }
    PROTOBUF_CONSTINIT const uint32_t AdditionResourceType_internal_data_[] = {
        589824u,
        0u,
    };
    bool AdditionResourceType_IsValid(int value)
    {
        return 0 <= value && value <= 8;
    }
    const ::google::protobuf::EnumDescriptor* EconomyResourceState_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[7];
    }
    PROTOBUF_CONSTINIT const uint32_t EconomyResourceState_internal_data_[] = {
        262144u,
        0u,
    };
    bool EconomyResourceState_IsValid(int value)
    {
        return 0 <= value && value <= 3;
    }
    const ::google::protobuf::EnumDescriptor* AdditionResourceState_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[8];
    }
    PROTOBUF_CONSTINIT const uint32_t AdditionResourceState_internal_data_[] = {
        262144u,
        0u,
    };
    bool AdditionResourceState_IsValid(int value)
    {
        return 0 <= value && value <= 3;
    }
    const ::google::protobuf::EnumDescriptor* EquipmentType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[9];
    }
    PROTOBUF_CONSTINIT const uint32_t EquipmentType_internal_data_[] = {
        720896u,
        0u,
    };
    bool EquipmentType_IsValid(int value)
    {
        return 0 <= value && value <= 10;
    }
    const ::google::protobuf::EnumDescriptor* ConstructionType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[10];
    }
    PROTOBUF_CONSTINIT const uint32_t ConstructionType_internal_data_[] = {
        262144u,
        0u,
    };
    bool ConstructionType_IsValid(int value)
    {
        return 0 <= value && value <= 3;
    }
    const ::google::protobuf::EnumDescriptor* TrapType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[11];
    }
    PROTOBUF_CONSTINIT const uint32_t TrapType_internal_data_[] = {
        196608u,
        0u,
    };
    bool TrapType_IsValid(int value)
    {
        return 0 <= value && value <= 2;
    }
    const ::google::protobuf::EnumDescriptor* NewsType_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[12];
    }
    PROTOBUF_CONSTINIT const uint32_t NewsType_internal_data_[] = {
        196608u,
        0u,
    };
    bool NewsType_IsValid(int value)
    {
        return 0 <= value && value <= 2;
    }
    const ::google::protobuf::EnumDescriptor* PlayerTeam_descriptor()
    {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
        return file_level_enum_descriptors_MessageType_2eproto[13];
    }
    PROTOBUF_CONSTINIT const uint32_t PlayerTeam_internal_data_[] = {
        196608u,
        0u,
    };
    bool PlayerTeam_IsValid(int value)
    {
        return 0 <= value && value <= 2;
    }
    // @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google
{
    namespace protobuf
    {
    }  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_MessageType_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
